### ISSUE TITLE
Plugin 'x' Has Unsupported Platform. (//)

### ISSUE THREAD

**Issue by Zetz512** [ModderGhost/MetaMod-C#4]
what that mean¿?¿? i get that with next modules:

VoiceTranscoder
SafeNameChat
FloodBlocker

but anyways these working

img: http://prntscr.com/nroy3k

img "meta list": http://prntscr.com/nroy5s

**Comment by ModderGhost** [comment]
Unsupported platform error can be caused from plugins.ini
Plugin platform should be 'win32' or 'mswin' otherwise error is thrown.
Most likely there is a formatting error.
